Header footer
ProsTuha/Lab_vue pull request #1
Opened 2021-11-29 11:15 UTC by ProsTuha

Added header and footer. Created "Home", "About", "Products" and "Error 404" pages. Worked with Vue-router.

2021-11-29 11:35 UTC, derkach-artem commented on public/styles/main.css
> +  }
Lint как бы намекает на то что тут должна быть пустая строка

2021-11-29 11:41 UTC, derkach-artem commented on src/components/footer-slogan.vue
> +<template>
Тут ошибки БЭМ.
У тебя есть блок footer, который как я понимаю делится на 2 элемента - slogan и logos. Следовательно нужно сдлать примерно так
.footer {}
.footer__slogan {}
.footer__logos {}
.footer__logos-item {} ( это ссылки <a></a> )

Селекторы по тегу - не самая лучшая идея. Переделать на классы

2021-11-29 13:17 UTC, derkach-artem requested changes

2021-11-29 13:17 UTC, derkach-artem commented on src/components/header-nav.vue
> +header {
Селектор тега переделать на класс

2021-11-29 13:17 UTC, derkach-artem commented on src/components/header-nav.vue
> +    a.router-link-active {
Класс активного элемента можно переопределить в конструкторе и после этого можно не повышать специфичность.
Пример: nav__link--active

2021-11-29 13:17 UTC, derkach-artem commented on src/pages/About.vue
> +
Если не используешь стили то тег style можно убрать

2021-11-29 13:17 UTC, derkach-artem commented on src/pages/Page404.vue
> +        <h1 class="error_page">404 Not Found!</h1>
Тег `<h1>` это не страница, поэтому название класса для этого тега не корректно

2021-11-29 13:17 UTC, derkach-artem commented on src/pages/Home.vue
> +        <h1 class="Home">Home!</h1>
Тег `<h1>` это не страница, поэтому название класса для этого тега не корректно

2021-11-29 13:17 UTC, derkach-artem commented on src/components/footer-slogan.vue
> +                <img src="../../public/img/rockstar-games-logo.png" alt="rc games">
1. В принципе, это хард код и пути к изображениям лучше вынести в переменные
2. что бы не  писать ../../ можно использовать алиас. На сколько я помню можно использовать @ и пути будут начинаться с папки src

2021-11-29 13:17 UTC, derkach-artem commented on src/components/header-nav.vue
> +.nav {
.nav {
   // styles for `.nav`
   
   &__logo {
      // styles for `.nav__logo`
      
      &__link {
         // styles for `.nav__logo__link`

         &::hover {
            //  // styles for `.nav__logo__link:hover`
         }
      }
   }
}

Идея надеюсь понятна? )))

2021-11-29 13:17 UTC, derkach-artem commented on src/components/header-nav.vue
> +    </header>
Тут с форматированием(отступы) проблема

2021-11-29 13:17 UTC, derkach-artem commented on public/styles/main.css
> +  #app {
Селекторы ID - не лучшая идея. Если прям очень хочется то на тег добавить класс и стилизовать его

2021-11-29 22:51 UTC, ProsTuha commented
Вроде бы всё исправил

2021-12-03 10:33 UTC, derkach-artem requested changes

2021-12-03 10:33 UTC, derkach-artem commented on src/components/footer-logos.vue
> +    <div class="footer__logos">
.footer-logos {

   // styles for block
   &__image {
       // styles for image
       
       &--mod-green {
          // styles for image modufy
       }
       
       &--mod-red {
         // styles for image modufy
       }
   }
}

2021-12-03 10:33 UTC, derkach-artem commented on src/components/header-nav.vue
> +    .active {
example
.nav__logo__link--active {
   // styles for active link
}

2021-12-03 10:33 UTC, derkach-artem commented on src/assets/normalize.css
> +}
Добавить пустую строку

2021-12-03 10:33 UTC, derkach-artem commented on src/assets/main-styles.scss
> +}
Добавить пустую строку

2021-12-03 10:33 UTC, derkach-artem commented on src/assets/colors.scss
> +$bg-navigation-hover: #272727;
Добавить пустую строку

2021-12-03 10:54 UTC, ProsTuha commented on src/assets/normalize.css
> +}
Добавил

2021-12-03 10:54 UTC, ProsTuha commented on src/assets/main-styles.scss
> +}
Добавил

2021-12-03 10:54 UTC, ProsTuha commented on src/assets/colors.scss
> +$bg-navigation-hover: #272727;
Добавил

2021-12-03 11:43 UTC, derkach-artem approved these changes

2021-12-03 11:52 UTC, merged