Product filtration
ProsTuha/Lab_vue pull request #10
Opened 2022-02-03 13:31 UTC by ProsTuha

2022-02-03 13:51 UTC, derkach-artem requested changes

2022-02-03 13:51 UTC, derkach-artem commented on src/pages/ProductsPage.vue
> +    if (this.ascending) {
![image](https://user-images.githubusercontent.com/24730289/152354391-51273e42-a7c3-4e85-8a73-2ec5dff491d2.png)

2022-02-03 14:01 UTC, derkach-artem requested changes

2022-02-03 14:01 UTC, derkach-artem commented on src/pages/ProductsPage.vue
> +    if (this.less) {
const sorted = products.filter((product) => {
  return less ? product.productPrice < price : product.productPrice > price
})

2022-02-07 12:51 UTC, derkach-artem requested changes

2022-02-07 12:51 UTC, derkach-artem commented on src/components/Loader.vue
> +  & div {
Селектор тега убрать

2022-02-07 12:51 UTC, derkach-artem commented on src/pages/ProductsPage.vue
> +          <div class="header__navigation__dropdown-content">
header-navigation

2022-02-07 12:51 UTC, derkach-artem commented on src/pages/ProductsPage.vue
> +  productSorting(): (a: any, b: any) => number {
почему any ?

2022-02-07 12:51 UTC, derkach-artem commented on src/pages/ProductsPage.vue
> +  productFiltering(): (product: any) => boolean {
исправь any

2022-02-07 14:16 UTC, ProsTuha commented on src/components/Loader.vue
> +  & div {
Убрал

2022-02-07 14:33 UTC, ProsTuha commented on src/pages/ProductsPage.vue
> +          <div class="header__navigation__dropdown-content">
Изменил

2022-02-07 14:39 UTC, ProsTuha commented on src/pages/ProductsPage.vue
> +  productFiltering(): (product: any) => boolean {
Исправил

2022-02-07 14:39 UTC, ProsTuha commented on src/pages/ProductsPage.vue
> +  productSorting(): (a: any, b: any) => number {
Исправил

2022-02-07 14:43 UTC, derkach-artem approved these changes

2022-02-07 14:44 UTC, merged