Shopping cart
ProsTuha/Lab_vue pull request #12
Opened 2022-02-10 05:12 UTC by ProsTuha

2022-02-14 12:01 UTC, derkach-artem requested changes

2022-02-14 12:01 UTC, derkach-artem commented on src/components/HeaderNavigation.vue
> +      color: $color-orange;
hover перенести сюда
&:hover {
      background: $color-orange;
      transition: background 0.5s;
      color: $color-pink;
}

2022-02-14 12:01 UTC, derkach-artem commented on src/components/HeaderNavigation.vue
> +      color: $color-pink;;
лишняя ;

2022-02-14 12:01 UTC, derkach-artem commented on src/components/ProductCard.vue
> +      return this.inCart ? 'Remove from cart' : 'Add to cart'
'Remove from cart' и 'Add to cart' в константы

2022-02-14 12:01 UTC, derkach-artem commented on src/pages/HomePage.vue
> +    this.alertMessage = value ? 'Successfully added to cart' : 'Successfully removed from cart'
Текст в константы

2022-02-14 12:01 UTC, derkach-artem commented on src/pages/ShoppingCart.vue
> +  createCaregory(id: number): string {
Это вообще не вариант ....
Тут нужно типизировать,  например, создай enum
enum Platform {
   PC,
   PS,
   Xbox
}

switch (id) {
   case Platform.PC: //
   case Platform.PS: //
   case Platform.Xbox: //
}

2022-02-15 04:23 UTC, ProsTuha commented on src/components/HeaderNavigation.vue
> +      color: $color-orange;
Исправил

2022-02-15 04:24 UTC, ProsTuha commented on src/components/HeaderNavigation.vue
> +      color: $color-pink;;
Убрал

2022-02-15 04:28 UTC, ProsTuha commented on src/components/ProductCard.vue
> +      return this.inCart ? 'Remove from cart' : 'Add to cart'
Сделал

2022-02-15 04:31 UTC, ProsTuha commented on src/pages/HomePage.vue
> +    this.alertMessage = value ? 'Successfully added to cart' : 'Successfully removed from cart'
Исправил

2022-02-15 04:46 UTC, ProsTuha commented on src/pages/ShoppingCart.vue
> +  createCaregory(id: number): string {
Поменял

2022-02-15 12:33 UTC, derkach-artem approved these changes

2022-02-16 05:07 UTC, merged