Checkout
ProsTuha/Lab_vue pull request #13
Opened 2022-02-14 05:07 UTC by ProsTuha

2022-02-14 12:05 UTC, derkach-artem requested changes

2022-02-14 12:05 UTC, derkach-artem commented on src/pages/DetailPage.vue
> +    this.alertMessage = 'First you need to log in / register'
ВСЕ текстовые строки в константы

2022-02-15 04:51 UTC, ProsTuha commented on src/pages/DetailPage.vue
> +    this.alertMessage = 'First you need to log in / register'
Изменил

2022-02-15 12:34 UTC, derkach-artem approved these changes

2022-02-16 05:08 UTC, merged